# Created with YamlCreate.ps1 v2.3.2 $debug=QUSU.CRLF.5-1-22621-2506.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Zulip.Zulip
PackageVersion: 5.10.5.0
PackageLocale: en-US
Publisher: Kandra Labs, Inc.
PublisherUrl: https://github.com/zulip/zulip-desktop
PublisherSupportUrl: https://github.com/zulip/zulip-desktop/issues
# PrivacyUrl:
Author: Kandra Labs, Inc.
PackageName: Zulip
PackageUrl: https://zulipchat.com
License: APACHE-2.0
LicenseUrl: https://raw.githubusercontent.com/zulip/zulip-desktop/main/LICENSE
# Copyright:
CopyrightUrl: https://raw.githubusercontent.com/zulip/zulip-desktop/main/LICENSE
ShortDescription: Desktop client for Zulip, an open source team chat application.
# Description:
Moniker: zulip
Tags:
- communication
- electron
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.5.0
