# Created with YamlCreate.ps1 v2.3.2 $debug=QUSU.CRLF.5-1-22621-2506.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: SatDump.SatDump
PackageVersion: 1.1.0
PackageLocale: en-US
Publisher: SatDump.org
PublisherUrl: https://github.com/SatDump/
PublisherSupportUrl: https://github.com/SatDump/SatDump/issues
PrivacyUrl: https://github.com/SatDump/SatDump/issues
Author: SatDump
PackageName: SatDump
PackageUrl: https://github.com/SatDump/SatDump/
License: GPL-3.0 license
LicenseUrl: https://github.com/SatDump/SatDump/blob/master/LICENSE
Copyright: Copyright (C) 2023 SatDump.org
CopyrightUrl: https://github.com/SatDump/SatDump/blob/master/LICENSE
ShortDescription: A generic satellite data processing software.
# Description:
Moniker: satdump
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.5.0
